target_sources(
	BloodrootApp
	PRIVATE 
		Window/Window.cpp
		Window/GLFWInstance.cpp
		Vulkan/VulkanRenderer.cpp
		Image/Image.cpp
		"Math/Noise/SimplexNoise.cpp"
		Data/Octree.cpp
		Vulkan/VMA/VMemAlloc.cpp
		Vulkan/VMA/VMemBuffer.cpp
	PUBLIC
	FILE_SET HEADERS
	FILES
		Window/Window.h
		Interfaces/IRenderer.h
		Window/GLFWInstance.h 
		Vulkan/VulkanRenderer.h 
		Vulkan/Geometry/Square.h 
		Vulkan/Geometry/Vertex.h 
		Vulkan/Geometry/Cube.h 
		Vulkan/Geometry/Mesh.h 
		Image/Image.h
		"Math/Noise/FastNoiseLite.h"
		"Math/Noise/SimplexNoise.h"
		Data/Octree.h
		Vulkan/VMA/VMemAlloc.h
		Vulkan/VMA/VMemBuffer.h
)

target_include_directories(
	BloodrootApp
	PUBLIC
		Window
		Interfaces
		Vulkan
		Vulkan/Geometry
		Image
		"Math/Noise"
		Data
		Vulkan/VMA
)

add_subdirectory(FileIO)
