target_sources(
	BloodrootApp
	PRIVATE 
		Vulkan/VulkanRenderer.cpp
		Image/Image.cpp
		"Math/Noise/SimplexNoise.cpp"
		Vulkan/VMA/VMAAllocator.cpp
		Vulkan/VMA/VMAVirtualBlock.cpp
		Vulkan/VMA/VMAImage.cpp
		Vulkan/Pipeline/GraphicsPipeline.cpp
		Vulkan/Material/Texture.cpp
		Vulkan/CommandBuffer/CommandBufferManager.cpp

	PUBLIC
	FILE_SET HEADERS
	FILES
		Interfaces/IRenderer.h
		Vulkan/VulkanRenderer.h
		Vulkan/VulkanHandles.h
		Vulkan/Geometry/Vertex.h 
		Vulkan/Geometry/Cube.h 
		Vulkan/Geometry/Mesh.h 
		Vulkan/Geometry/Quad.h
		Image/Image.h
		"Math/Noise/FastNoiseLite.h"
		"Math/Noise/SimplexNoise.h"
		Vulkan/VMA/VMAAllocator.h
		Vulkan/VMA/VMABuffer.h
		Vulkan/VMA/VMAVirtualBlock.h
		Vulkan/VMA/VMAVirtualAllocation.h
		Vulkan/VMA/VMAImage.h
		Extensions/GLMExtensions.h
		"Math/RLEncoding/RLEncoding.h"
		Vulkan/Pipeline/GraphicsPipeline.h
		Vulkan/Pipeline/ShaderModule.h
		Vulkan/Material/Texture.h
		Vulkan/CommandBuffer/CommandBufferManager.h
		SDL3/SDL3Instance.h
		SDL3/Window/Window.h
		"Math/Random/Random.h"
		"Math/Geometry.h"
)

target_include_directories(
	BloodrootApp
	PUBLIC
		Interfaces
		Vulkan
		Vulkan/Geometry
		Vulkan/Material
		Image
		"Math"
		"Math/Noise"
		"Math/RLEncoding"
		"Math/Random"
		Data
		Vulkan/VMA
		Vulkan/Pipeline
		Extensions
		Vulkan/CommandBuffer
		SDL3
		SDL3/Window
)

add_subdirectory(FileIO)
