target_sources(
	BloodrootApp
	PRIVATE 
		Window/Window.cpp
		Window/GLFWInstance.cpp
		Vulkan/VulkanRenderer.cpp
		Image/Image.cpp
		"Math/Noise/SimplexNoise.cpp"
		Vulkan/VMA/VMAAllocator.cpp
		Vulkan/VMA/VMAVirtualBlock.cpp
		Vulkan/Pipeline/GraphicsPipeline.cpp

	PUBLIC
	FILE_SET HEADERS
	FILES
		Window/Window.h
		Interfaces/IRenderer.h
		Window/GLFWInstance.h 
		Vulkan/VulkanRenderer.h 
		Vulkan/Geometry/Square.h 
		Vulkan/Geometry/Vertex.h 
		Vulkan/Geometry/Cube.h 
		Vulkan/Geometry/Mesh.h 
		Image/Image.h
		"Math/Noise/FastNoiseLite.h"
		"Math/Noise/SimplexNoise.h"
		Vulkan/VMA/VMAAllocator.h
		Vulkan/VMA/VMABuffer.h
		Vulkan/VMA/VMAVirtualBlock.h
		Vulkan/VMA/VMAVirtualAllocation.h
		Extensions/GLMExtensions.h
		"Math/RLEncoding/RLEncoding.h"
		Vulkan/Pipeline/GraphicsPipeline.h
)

target_include_directories(
	BloodrootApp
	PUBLIC
		Window
		Interfaces
		Vulkan
		Vulkan/Geometry
		Image
		"Math"
		"Math/Noise"
		"Math/RLEncoding"
		Data
		Vulkan/VMA
		Vulkan/Pipeline
		Extensions
)

add_subdirectory(FileIO)
